site_url: https://fortbendlinc.org
local_backend: false
backend:
  name: git-gateway
  branch: cms # Branch to update (optional; defaults to master)
  # repo: mokshadata/linc-demo
  # base_url: https://api.netlify.com
collections:
  - name: "steps" # Used in routes, e.g., /admin/collections/blog
    label: "Step" # Used in the UI
    folder: "src/content/steps" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
      - label: "Featured Image"
        name: "cover"
        widget: "image"
        media_folder: "/src/content/steps"
      - { label: "Featured Image Description", name: "coverAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "faqs"
    label: "FAQs"
    folder: "src/content/faqs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "photos"
    label: "Photo Grid"
    folder: "src/content/grid"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Column", name: "column", widget: "number" }
      - { label: "Order", name: "order", widget: "number" }
      - label: "Image Filename"
        name: "image_filename"
        widget: "image"
        choose_url: false
        media_folder: "/src/assets/images/grid/compressed"
        default: "/src/assets/images/grid/compressed/family-bike.jpg"
        media_library:
          config:
            multiple: false
      - { label: "Alt", name: "alt", widget: "string" }
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media